/**
 * fabricClient.js
 *
 * Two root-cause fixes applied here:
 *
 * 1. CHANNELS SECTION MISSING: The connection profile generated by fabric-samples
 *    does not include a `channels` section.  Without it, the Node SDK (with
 *    discovery disabled) has no idea which peers serve which channel, so every
 *    query returns "Query failed. Errors: []".
 *    FIX → we inject the channels section programmatically before connecting.
 *
 * 2. WRONG ADMIN IDENTITY: enrolling via `fabric-ca-client` gives an identity
 *    without the ADMIN OU (it's just a regular user cert).  The peer rejects
 *    lifecycle / admin-ACL calls with "The identity is not an admin under this MSP".
 *    FIX → we load the real Org1 Admin cert+key from the network crypto material
 *          (network/organizations/peerOrganizations/org1.example.com/users/Admin@...)
 *
 * 3. DISCOVERY DISABLED: on Windows + Docker, service-discovery returns internal
 *    Docker hostnames that Windows cannot resolve → gRPC timeout.
 *    FIX → discovery: { enabled: false }  (uses static endpoints from CCP).
 */

const { Gateway, Wallets } = require('fabric-network');
const path = require('path');
const fs   = require('fs');

// ── helpers ────────────────────────────────────────────────────────────────────
function findFile(dir, pattern) {
  if (!fs.existsSync(dir)) return null;
  const files = fs.readdirSync(dir).filter(f => pattern.test(f));
  return files.length ? path.join(dir, files[0]) : null;
}

// ── main class ────────────────────────────────────────────────────────────────
class FabricClient {
  constructor() {
    this.wallet   = null;
    this.gateway  = null;
    this.network  = null;
    this.contract = null;
    this._ready   = false;
    this._initPromise = null;
  }

  async initialize() {
    if (this._ready)       return true;
    if (this._initPromise) return this._initPromise;

    this._initPromise = this._doInitialize()
      .then(v  => { this._ready = true;  this._initPromise = null; return v; })
      .catch(e => { this._ready = false; this._initPromise = null; throw e; });

    return this._initPromise;
  }

  async _doInitialize() {
    // ── 1. Load connection profile ──────────────────────────────────────────
    const ccpPath = path.resolve(
      process.cwd(),
      process.env.CONNECTION_PROFILE_PATH ||
        '../network/organizations/peerOrganizations/org1.example.com/connection-org1.json'
    );
    if (!fs.existsSync(ccpPath)) throw new Error(`Connection profile not found: ${ccpPath}`);

    const ccp = JSON.parse(fs.readFileSync(ccpPath, 'utf8'));

    const channelName   = process.env.CHANNEL_NAME   || process.env.FABRIC_CHANNEL_NAME   || 'ridechannel';
    const chaincodeName = process.env.CHAINCODE_NAME || process.env.FABRIC_CHAINCODE_NAME || 'rideshare';
    const mspId         = process.env.MSP_ID         || process.env.FABRIC_MSP_ID         || 'Org1MSP';

    // ── 2. INJECT channels section (missing from fabric-samples template) ───
    //    Without this, the SDK (discovery=false) cannot route queries to peers.
    const peerNames = Object.keys(ccp.peers || {});
    if (!ccp.channels) {
      ccp.channels = {};
    }
    if (!ccp.channels[channelName]) {
      const peersMap = {};
      peerNames.forEach(p => {
        peersMap[p] = {
          endorsingPeer:  true,
          chaincodeQuery: true,
          ledgerQuery:    true,
          eventSource:    true,
        };
      });
      ccp.channels[channelName] = { peers: peersMap };
      console.log(`ℹ️  Injected channels.${channelName} with peers: [${peerNames.join(', ')}]`);
    }

    // ── 3. Wallet: load real Org Admin identity from network crypto ─────────
    const walletPath = path.join(process.cwd(), process.env.WALLET_PATH || 'wallet');
    this.wallet = await Wallets.newFileSystemWallet(walletPath);

    const IDENTITY_LABEL = 'orgAdmin';
    const existing = await this.wallet.get(IDENTITY_LABEL);
    if (!existing) {
      await this._loadOrgAdmin(mspId, IDENTITY_LABEL);
    }

    // ── 4. Connect gateway — discovery DISABLED (Windows+Docker workaround) ─
    this.gateway = new Gateway();
    await this.gateway.connect(ccp, {
      wallet:    this.wallet,
      identity:  IDENTITY_LABEL,
      discovery: { enabled: false, asLocalhost: false },
    });

    this.network  = await this.gateway.getNetwork(channelName);
    this.contract = this.network.getContract(chaincodeName);

    console.log(`✅ Fabric connected  channel=${channelName}  cc=${chaincodeName}  id=${IDENTITY_LABEL}`);
    return true;
  }

  /** Load Admin@org1.example.com cert+key from network crypto material */
  async _loadOrgAdmin(mspId, label) {
    const networkRoot = path.resolve(process.cwd(), '..', 'network', 'organizations',
      'peerOrganizations', 'org1.example.com', 'users', 'Admin@org1.example.com', 'msp');

    const signCertsDir = path.join(networkRoot, 'signcerts');
    const keystoreDir  = path.join(networkRoot, 'keystore');

    if (!fs.existsSync(signCertsDir) || !fs.existsSync(keystoreDir)) {
      throw new Error(
        `Network admin MSP not found at ${networkRoot}. ` +
        'Ensure the Fabric network has been started and crypto material generated.'
      );
    }

    // cert — usually cert.pem or a hash.pem
    const certFile = findFile(signCertsDir, /\.pem$/) || findFile(signCertsDir, /.*/);
    if (!certFile) throw new Error(`No cert found in ${signCertsDir}`);

    // key — the _sk file in keystore
    const keyFile = findFile(keystoreDir, /_sk$/) || findFile(keystoreDir, /\.pem$/) || findFile(keystoreDir, /.*/);
    if (!keyFile) throw new Error(`No private key found in ${keystoreDir}`);

    const certificate = fs.readFileSync(certFile, 'utf8');
    const privateKey  = fs.readFileSync(keyFile,  'utf8');

    await this.wallet.put(label, {
      credentials: { certificate, privateKey },
      mspId,
      type: 'X.509',
    });

    console.log(`✅ Org admin identity loaded from network crypto  (label=${label})`);
  }

  // ── Transactions ─────────────────────────────────────────────────────────────
  async submitTransaction(functionName, ...args) {
    await this.initialize();
    try {
      const result = await this.contract.submitTransaction(functionName, ...args);
      return result ? result.toString() : '';
    } catch (err) {
      console.error(`❌ Submit [${functionName}]: ${err.message}`);
      throw err;
    }
  }

  async evaluateTransaction(functionName, ...args) {
    await this.initialize();
    try {
      const result = await this.contract.evaluateTransaction(functionName, ...args);
      return result ? result.toString() : 'null';
    } catch (err) {
      console.error(`❌ Query  [${functionName}]: ${err.message}`);
      throw err;
    }
  }

  async disconnect() {
    if (this.gateway) {
      await this.gateway.disconnect();
      this._ready = false;
      console.log('✅ Disconnected from Fabric');
    }
  }
}

module.exports = new FabricClient();
